import { useEffect, useState, type JSX } from 'react';
import { automations as automationsIpc } from '../../lib/ipc';
import type { Automation } from '../../lib/types';
import { PROVIDERS } from '../../providers/registry';
import { useApp } from '../../store/app';
import { Button, Card, Chip, Field, Muted, Toggle } from './ui';
import { formatDateTime, hostTimezone, pad2 } from './format';
import { HOURS, MINUTES, PRESETS, inferPreset, type Preset } from './schedule';

type WorkspaceMode = 'new_worktree' | 'pinned';

interface FormState {
  name: string;
  prompt: string;
  projectId: string | null;
  preset: Preset;
  hour: number;
  minute: number;
  rrule: string;
  timezone: string;
  providerId: string;
  policy: string;
  workspaceMode: WorkspaceMode;
  pinnedSessionId: string | null;
  continueSession: boolean;
  catchUp: boolean;
}

const POLICIES: { value: string; label: string }[] = [
  { value: 'ask', label: 'Ask' },
  { value: 'auto-edits', label: 'Auto edits' },
  { value: 'bypass', label: 'Bypass' },
];

function initialState(automation: Automation | null, defaultTimezone: string): FormState {
  if (!automation) {
    return {
      name: '',
      prompt: '',
      projectId: null,
      preset: 'daily',
      hour: 9,
      minute: 0,
      rrule: 'FREQ=DAILY;BYHOUR=9;BYMINUTE=0',
      timezone: defaultTimezone,
      providerId: PROVIDERS[0]?.id ?? '',
      policy: 'auto-edits',
      workspaceMode: 'new_worktree',
      pinnedSessionId: null,
      continueSession: false,
      catchUp: false,
    };
  }
  const inferred = inferPreset(automation.rrule);
  return {
    name: automation.name,
    prompt: automation.prompt,
    projectId: automation.project_id,
    preset: inferred.preset,
    hour: inferred.hour,
    minute: inferred.minute,
    rrule: automation.rrule,
    timezone: automation.timezone || defaultTimezone,
    providerId: automation.provider_id,
    policy: automation.permission_policy || 'auto-edits',
    workspaceMode: automation.workspace_mode,
    pinnedSessionId: automation.pinned_session_id,
    continueSession: automation.continue_agent_session,
    catchUp: automation.catch_up,
  };
}

export function AutomationForm({
  automation = null,
  onSaved,
  onCancel,
}: {
  automation?: Automation | null;
  onSaved: (saved: Automation) => void;
  onCancel?: () => void;
}): JSX.Element {
  const projects = useApp((s) => s.projects);
  const sessions = useApp((s) => s.sessions);
  const refreshAutomations = useApp((s) => s.refreshAutomations);
  const defaultTimezone = useApp((s) => s.settings.default_timezone) || hostTimezone();

  const [form, setForm] = useState<FormState>(() => initialState(automation, defaultTimezone));
  const [preview, setPreview] = useState<string[]>([]);
  const [previewError, setPreviewError] = useState<string | null>(null);
  const [checking, setChecking] = useState(false);
  const [saving, setSaving] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);

  const patch = (next: Partial<FormState>) => setForm((prev) => ({ ...prev, ...next }));

  // The next three fires, refreshed once typing settles.
  useEffect(() => {
    const rule = form.rrule.trim();
    if (!rule) {
      setPreview([]);
      setPreviewError('A schedule rule is required.');
      return;
    }
    let cancelled = false;
    setChecking(true);
    const id = window.setTimeout(() => {
      automationsIpc
        .schedulePreview(rule, form.timezone.trim() || hostTimezone())
        .then((next) => {
          if (cancelled) return;
          setPreview(next);
          setPreviewError(next.length === 0 ? 'This rule never fires.' : null);
        })
        .catch((e: unknown) => {
          if (cancelled) return;
          setPreview([]);
          setPreviewError(String(e));
        })
        .finally(() => {
          if (!cancelled) setChecking(false);
        });
    }, 350);
    return () => {
      cancelled = true;
      window.clearTimeout(id);
    };
  }, [form.rrule, form.timezone]);

  // Presets are generated by the backend so the app and the scheduler never disagree.
  const applyPreset = (preset: Preset, hour: number, minute: number) => {
    if (preset === 'custom') {
      patch({ preset, hour, minute });
      return;
    }
    patch({ preset, hour, minute });
    automationsIpc
      .presetRrule(preset, hour, minute)
      .then((rule) => patch({ rrule: rule }))
      .catch((e: unknown) => setPreviewError(String(e)));
  };

  const projectSessions = sessions.filter(
    (s) => s.project_id === form.projectId && !s.archived_at,
  );
  const pinned = form.workspaceMode === 'pinned';
  const sessionChipEnabled = pinned && !!form.pinnedSessionId;

  const invalid =
    !form.name.trim() ||
    !form.prompt.trim() ||
    !form.rrule.trim() ||
    !form.providerId ||
    previewError !== null ||
    (pinned && !form.pinnedSessionId);

  const save = () => {
    if (invalid || saving) return;
    setSaving(true);
    setSaveError(null);
    automationsIpc
      .save({
        ...(automation ? { id: automation.id } : {}),
        name: form.name.trim(),
        prompt: form.prompt,
        provider_id: form.providerId,
        project_id: form.projectId,
        rrule: form.rrule.trim(),
        timezone: form.timezone.trim() || hostTimezone(),
        workspace_mode: form.workspaceMode,
        pinned_session_id: pinned ? form.pinnedSessionId : null,
        continue_agent_session: pinned ? form.continueSession : false,
        permission_policy: form.policy,
        catch_up: form.catchUp,
      })
      .then(async (saved) => {
        await refreshAutomations();
        onSaved(saved);
      })
      .catch((e: unknown) => setSaveError(String(e)))
      .finally(() => setSaving(false));
  };

  return (
    <div className="flex flex-col gap-8">
      <Card>
        <Field step={1} label="Title" hint="What this automation is for, in a few words.">
          <input
            className="w-full"
            value={form.name}
            placeholder="Morning dependency sweep"
            onChange={(e) => patch({ name: e.target.value })}
          />
        </Field>
      </Card>

      <Card>
        <Field
          step={2}
          label="Prompt"
          hint="Markdown. This is sent to the agent verbatim on every fire, so write it as a standing instruction rather than a one-off ask."
        >
          <textarea
            className="w-full font-mono"
            style={{ fontSize: 'var(--bt-code-size)', lineHeight: 1.6, resize: 'vertical' }}
            rows={10}
            spellCheck={false}
            value={form.prompt}
            placeholder={'Check for outdated dependencies.\n\nOpen a PR if anything is more than one major version behind.'}
            onChange={(e) => patch({ prompt: e.target.value })}
          />
        </Field>
      </Card>

      <Card>
        <Field step={3} label="Device" hint="Where the agent process runs.">
          <select className="w-full max-w-sm" value="local" disabled aria-label="Device">
            <option value="local">This device (local)</option>
          </select>
        </Field>
        <p className="mt-2" style={{ color: 'var(--bt-text-faint)' }}>
          Only this device exists today. Remote devices arrive with LAN pairing, and this select
          opens up then.
        </p>
      </Card>

      <Card>
        <Field
          step={4}
          label="Project"
          hint="The repository each run works in."
        >
          <select
            className="w-full max-w-md"
            value={form.projectId ?? ''}
            onChange={(e) => {
              const value = e.target.value || null;
              patch({ projectId: value, pinnedSessionId: null });
            }}
          >
            <option value="">No project</option>
            {projects.map((project) => (
              <option key={project.id} value={project.id}>
                {project.name}
              </option>
            ))}
          </select>
        </Field>
        <p className="mt-2 max-w-[70ch]" style={{ color: 'var(--bt-text-faint)' }}>
          “No project” runs each fire in a scratch directory — no worktree, no branch, and no diff to
          review afterwards.
        </p>
      </Card>

      <Card>
        <Field step={5} label="Schedule" hint="When this fires.">
          <div className="flex flex-col gap-4">
            <div className="flex flex-wrap gap-2">
              {PRESETS.map((preset) => {
                const active = preset.value === form.preset;
                return (
                  <button
                    key={preset.value}
                    type="button"
                    aria-pressed={active}
                    onClick={() => applyPreset(preset.value, form.hour, form.minute)}
                    className="px-3 py-1.5"
                    style={{
                      background: active ? 'var(--bt-surface-3)' : 'var(--bt-surface-2)',
                      border: `1px solid ${active ? 'var(--bt-accent)' : 'var(--bt-border)'}`,
                      color: active ? 'var(--bt-accent)' : 'var(--bt-text-dim)',
                    }}
                  >
                    {preset.label}
                  </button>
                );
              })}
            </div>

            {form.preset === 'custom' ? (
              <div className="flex flex-col gap-1.5">
                <span style={{ color: 'var(--bt-text-dim)' }}>RRULE</span>
                <input
                  className="w-full font-mono"
                  style={{ fontSize: 'var(--bt-code-size)' }}
                  spellCheck={false}
                  aria-label="Recurrence rule"
                  value={form.rrule}
                  placeholder="FREQ=MINUTELY;INTERVAL=2"
                  onChange={(e) => patch({ rrule: e.target.value })}
                />
              </div>
            ) : (
              <div className="flex flex-wrap items-end gap-4">
                {form.preset !== 'hourly' ? (
                  <div className="flex flex-col gap-1.5">
                    <span style={{ color: 'var(--bt-text-dim)' }}>Hour</span>
                    <select
                      value={form.hour}
                      aria-label="Hour"
                      onChange={(e) => applyPreset(form.preset, Number(e.target.value), form.minute)}
                    >
                      {HOURS.map((h) => (
                        <option key={h} value={h}>
                          {pad2(h)}
                        </option>
                      ))}
                    </select>
                  </div>
                ) : null}
                <div className="flex flex-col gap-1.5">
                  <span style={{ color: 'var(--bt-text-dim)' }}>Minute</span>
                  <select
                    value={form.minute}
                    aria-label="Minute"
                    onChange={(e) => applyPreset(form.preset, form.hour, Number(e.target.value))}
                  >
                    {MINUTES.map((m) => (
                      <option key={m} value={m}>
                        {pad2(m)}
                      </option>
                    ))}
                  </select>
                </div>
                <div className="flex flex-col gap-1.5 flex-1 min-w-[16rem]">
                  <span style={{ color: 'var(--bt-text-faint)' }}>Rule</span>
                  <span
                    className="font-mono px-3 py-1.5 break-all"
                    style={{
                      background: 'var(--bt-surface-2)',
                      border: '1px solid var(--bt-border)',
                      color: 'var(--bt-text-dim)',
                      fontSize: 'var(--bt-code-size)',
                    }}
                  >
                    {form.rrule || '—'}
                  </span>
                </div>
              </div>
            )}

            <div className="flex flex-col gap-1.5 max-w-sm">
              <span style={{ color: 'var(--bt-text-dim)' }}>Timezone</span>
              <input
                className="w-full font-mono"
                style={{ fontSize: 'var(--bt-code-size)' }}
                spellCheck={false}
                aria-label="Timezone"
                value={form.timezone}
                placeholder={hostTimezone()}
                onChange={(e) => patch({ timezone: e.target.value })}
              />
            </div>

            <div
              className="p-4 flex flex-col gap-2"
              style={{ background: 'var(--bt-surface-2)', border: '1px solid var(--bt-border)' }}
            >
              <span style={{ color: 'var(--bt-text-dim)' }}>Next three fires</span>
              {previewError ? (
                <span style={{ color: 'var(--bt-removed)' }}>{previewError}</span>
              ) : checking ? (
                <span style={{ color: 'var(--bt-text-faint)' }}>Checking…</span>
              ) : preview.length === 0 ? (
                <span style={{ color: 'var(--bt-text-faint)' }}>Nothing scheduled.</span>
              ) : (
                <ol className="list-none m-0 p-0 flex flex-col gap-1">
                  {preview.map((iso) => (
                    <li key={iso} style={{ color: 'var(--bt-text)' }}>
                      {formatDateTime(iso)}
                    </li>
                  ))}
                </ol>
              )}
            </div>
          </div>
        </Field>
      </Card>

      <Card>
        <Field step={6} label="Agent" hint="Which CLI runs the prompt.">
          <select
            className="w-full max-w-sm"
            value={form.providerId}
            onChange={(e) => patch({ providerId: e.target.value })}
          >
            {PROVIDERS.map((provider) => (
              <option key={provider.id} value={provider.id}>
                {provider.name}
              </option>
            ))}
          </select>
        </Field>
      </Card>

      <Card>
        <Field step={7} label="Permission policy" hint="How much the agent may do without asking.">
          <div className="flex flex-wrap gap-2">
            {POLICIES.map((policy) => {
              const active = policy.value === form.policy;
              return (
                <button
                  key={policy.value}
                  type="button"
                  aria-pressed={active}
                  onClick={() => patch({ policy: policy.value })}
                  className="px-3 py-1.5"
                  style={{
                    background: active ? 'var(--bt-surface-3)' : 'var(--bt-surface-2)',
                    border: `1px solid ${active ? 'var(--bt-accent)' : 'var(--bt-border)'}`,
                    color: active ? 'var(--bt-accent)' : 'var(--bt-text-dim)',
                  }}
                >
                  {policy.label}
                </button>
              );
            })}
          </div>
        </Field>
        <p className="mt-2 max-w-[70ch]" style={{ color: 'var(--bt-text-faint)' }}>
          Nobody is watching an unattended run, so “Ask” will stall it at the first prompt until you
          open the session yourself.
        </p>
      </Card>

      <Card>
        <Field step={8} label="Scope" hint="Where the work lands and what the agent remembers.">
          <div className="flex flex-col gap-4">
            <p className="m-0 max-w-[70ch]" style={{ color: 'var(--bt-text)' }}>
              Every fire runs in a
              <Chip
                onClick={() =>
                  patch({
                    workspaceMode: pinned ? 'new_worktree' : 'pinned',
                    continueSession: pinned ? false : form.continueSession,
                  })
                }
              >
                {pinned ? 'Pinned worktree' : 'New worktree per run'}
              </Chip>
              with
              <Chip
                disabled={!sessionChipEnabled}
                title={
                  sessionChipEnabled
                    ? undefined
                    : 'Continuing a session needs a pinned worktree and a chosen session.'
                }
                onClick={() => patch({ continueSession: !form.continueSession })}
              >
                {sessionChipEnabled && form.continueSession
                  ? 'Continue previous session'
                  : 'Fresh agent each run'}
              </Chip>
              .
            </p>

            {!pinned ? (
              <Muted>
                Continuing a session needs a pinned worktree — a brand new worktree has no previous
                conversation to pick up.
              </Muted>
            ) : null}

            {pinned ? (
              <div className="flex flex-col gap-1.5 max-w-md">
                <span style={{ color: 'var(--bt-text-dim)' }}>Pinned session</span>
                <select
                  aria-label="Pinned session"
                  value={form.pinnedSessionId ?? ''}
                  onChange={(e) => patch({ pinnedSessionId: e.target.value || null })}
                >
                  <option value="">Choose a session…</option>
                  {projectSessions.map((session) => (
                    <option key={session.id} value={session.id}>
                      {session.name}
                    </option>
                  ))}
                </select>
                {projectSessions.length === 0 ? (
                  <Muted>
                    {form.projectId
                      ? 'This project has no sessions yet. Start one, then pin it here.'
                      : 'Pick a project above to choose one of its sessions.'}
                  </Muted>
                ) : null}
              </div>
            ) : null}
          </div>
        </Field>
      </Card>

      <Card>
        <Field step={9} label="Catch up on launch">
          <Toggle
            label="Run a missed fire at launch"
            hint="A fire that came due while Backtick was closed is skipped unless this is on. With it on, the most recent missed fire runs as soon as Backtick opens."
            checked={form.catchUp}
            onChange={(v) => patch({ catchUp: v })}
          />
        </Field>
      </Card>

      {saveError ? (
        <p className="m-0" style={{ color: 'var(--bt-removed)' }}>
          Could not save — {saveError}
        </p>
      ) : null}

      <div className="flex items-center gap-3">
        <Button variant="accent" disabled={invalid || saving} onClick={save}>
          {saving ? 'Saving…' : automation ? 'Save changes' : 'Create automation'}
        </Button>
        {onCancel ? <Button onClick={onCancel}>Cancel</Button> : null}
        {previewError ? (
          <span style={{ color: 'var(--bt-text-faint)' }}>
            Saving is blocked until the schedule is valid.
          </span>
        ) : null}
      </div>
    </div>
  );
}
